name: Publish Python Package to GPR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish Python package to GPR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: List files for debugging
        run: ls -R

      - name: Build package
        run: python -m build

      - name: Publish package to GitHub Packages
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.GITHUB_TOKEN }}
          repository_url: https://pypi.pkg.github.com/bnlnpps
